### ISSUE TITLE
When CultureInfo.CurrentCulture is "zh-CN", the PluralizationService.CreateService failed

### ISSUE THREAD

**Issue by jiaqun-zhang** [ernestoherrera/ErnestoHerrera.github.io#1]
Hi ErnestoHerrera,
I am Jack and come from China, when I use FluentSql, I found one issue with Culture. Here is detail:
When CultureInfo.CurrentCulture is "zh-CN", the PluralizationService.CreateService failed.
Could you please kindly fix this issue?

BR/Jack

**Comment by ernestoherrera** [comment]
Thank you Jack. I normally do not look into this repository for issues about the FluentSql. 
Next time please go to https://github.com/ernestoherrera/FluentSql this is where the code repository lives.

I will take a look at it, and make a comment there.
Ernesto.
